sudo:
    - false
    
language: 
    - cpp

compiler:
    - gcc

before_install:
    - sudo apt-get update
    - sudo apt-get install ffmpeg

script: 
    mkdir build && cd build && cmake .. && make && make check

notifications:
    recipients:
        - hello@cedric.ws
    irc: "chat.freenode.net#kerberos.io"
    email:
        on_success: always
        on_failure: always

os:
    - linux
    - osx
